var selected = null;

//These colors aren't completely arbitrary. I used a color scheme designer so they go together nicely.
var	compGenNum = '#000000'; //Variable for when a number is generated by the computer.
var userGenNum = '#033E6B'; //User generated number.
var mouseHover = '#FFEC73';	//No comment needed.
var mouseClicked = '#FFDD00';
var emptyBG = '#EDEDED';

var sudokuAnswer = generateBoard(true); //This is...the matrix.
var sudoku=sudokuAnswer;

window.onload = function() {
	for(i = 1; i < 10; i++) {
		for(j = 1; j < 10; j++) {
			var c = document.getElementById("row"+i+"_col"+j);
			
			c.onmouseover = pickSquare;
			c.onmouseout = mouseOut;
			c.onclick = makeChoice;
			
			var ctx=c.getContext('2d');
			ctx.fillStyle=emptyBG;
			ctx.fillRect(0, 0, 300, 300);
			paintNumber(c);
		}
	}
}

function mouseOut(){
	var c = document.getElementById(this.id);
	var ctx=c.getContext('2d');
	ctx.fillStyle=emptyBG;
	ctx.fillRect(0, 0, 300, 300);
	paintNumber(c);

	if(selected != null) {
		var ctx = selected.getContext('2d');
		ctx.fillStyle=mouseClicked;
		ctx.fillRect(0, 0, 300, 300);
		paintNumber(selected);
	}
}

function makeChoice(){
	if(selected != null) {
		var ctx = selected.getContext('2d');
		ctx.fillStyle=emptyBG;
		ctx.fillRect(0, 0, 300, 300);
		paintNumber(selected);
	}

	selected = document.getElementById(this.id);
	var ctx = selected.getContext('2d');
	ctx.fillStyle=mouseClicked;
	ctx.fillRect(0, 0, 300, 300);
	paintNumber(selected);
}

function pickSquare(){
	var c = document.getElementById(this.id);
	var ctx=c.getContext('2d');
	ctx.fillStyle=mouseHover;
	ctx.fillRect(0, 0, 300, 300);
	paintNumber(c);
}



//TODO
//called after square is selected, and number button (to be implented) or number on keyboard is pressed
function setSquareNumber() {
	/*
	if move is over a default placed value then dont paint it
	else if move has no conflicts then paint number selected
	else if move has conflicts then highlight conflicting square
	
	NOTE: if user has entered a number before, it can be overridden.
	*/
}

//TODO
//generate a complete 2d array of a valid board, and paint several starting numbers
function generateBoard(answerKey) {
	/*
	1. generate the 2D array
	2. paint numbers on random squares (or not-so-random)
	3. Paint the starting squares with faint transparent background (obviously different to user)
	*/

	//[row][column][Is computer generated]



	if(answerKey){
		newBoard = compSudoku();
	} else{
		newBoard = compSudoku();
	}
	return newBoard;
}

//TODO
//paints the square's number
function paintNumber(square) {
	/*
	square should be validated already, this should be a simple helper function. 
	*/
	//var c = document.getElementById(this.id);
	//Getting its location.
	//It's a stripper. Give it a dollar.

	//Apparently, "Your[my] stuff is purdy."
	name=square.getAttribute('id');
	nameArray=name.split("_");
	name=sudoku[nameArray[0][3]-1][nameArray[1][3]-1][0];

	var ctx=square.getContext('2d');
	ctx.textAlign = 'center';

	if(sudoku[nameArray[0][3]-1][nameArray[1][3]-1][1]){ //Computer generated = true
		ctx.font = 'Bold 100pt sans-serif';
		ctx.fillStyle=compGenNum;
		ctx.fillText(name,150,125);
	} else {
		ctx.font = 'Bold Italic 90pt sans-serif';
		ctx.fillStyle=userGenNum;
		ctx.fillText(name,150,120);
	}
}

//TODO
//Returns a boolean value. True if the board is complete.
function isComplete() {
	/*
	SHOULD NOT check only against our solution. Possible solution could differ from ours. 
	JON LEWIS TODO: Research board uniqness. 
		DONE: Board solutions are unique. Needs only to check against our solutions.
	*/
}

function compSudoku() { //Generates a valid sudoku
	var randRow = new Array(9);
	var newBoard=new Array(9),valid;
	var currentVal;
	for(i = 0; i < 9; i++) {
		newBoard[i]=new Array(9);
		for(j = 0; j < 9; j++) {
			newBoard[i][j]=new Array(2);
			newBoard[i][j][0]="_";
			newBoard[i][j][1]=true;
		}
	}

	for(i=0;i<9;i++){
		for(j=0;j<9;j++){
			for(n=0;n<9;n++){
				randRow[n]=n+1;
				if(newBoard[i][j][0]==randRow[n]){
					randRow.pop();
				}
			}
			randRow=shuffle(randRow);
			for(a=0;a<9;a++){
				currentVal=newBoard[i][a][0];
				if(randRow.indexOf(currentVal)>=0){
					delete randRow[randRow.indexOf(currentVal)];
				}
			}
			for(a=0;a<9;a++){
				currentVal=newBoard[a][j][0];
				if(randRow.indexOf(currentVal)>=0){
					delete randRow[randRow.indexOf(currentVal)];
				}
			}

			while(randRow.length>0&&randRow[0]==null){
				randRow.shift();
			}
			if(randRow.length==0){
				if(i>0){
					i--;
				} else {
					j--;
					i=8;
				}
			} else {
				newBoard[i][j][0]=randRow[0];
			}
		}
	}
	return newBoard;
}
function shuffle(array) {
  var m = array.length, t, i;

  // While there remain elements to shuffle…
  while (m) {

    // Pick a remaining element…
    i = Math.floor(Math.random() * m--);

    // And swap it with the current element.
    t = array[m];
    array[m] = array[i];
    array[i] = t;
  }

  return array;
}